### ISSUE TITLE
Object destroyed timeout

### ISSUE THREAD

**Issue by mattgarrish** [daisy/ace-gui#100]
I'm trying to run a file through the Ace GUI but it just spins for a couple of minutes and finally crashes out with an uncaught exception that an object has been destroyed at Timeout.timeoutFunc. I'll attach a screengrab below.

This is running the latest version of the Ace GUI on Win10. I only get the issue with this one file.

I can run the file successfully from the command line, but it takes a long time to complete. A couple of backmatter files, in particular, take a couple of minutes each.

Message me offline and I can point you to the file; it's in a daisy dropbox folder.

<img width="732" alt="timeout" src="https://user-images.githubusercontent.com/1565164/74587621-89f96600-4fcb-11ea-9625-66998c85aea0.PNG">

**Comment by danielweck** [comment]
I believe this is fixed in the latest version available in the release section of this GitHub project. The fix is to allow a maximum of 8 minutes of evaluation for each HTML document in the publication, beyond which point a timeout is triggered that fails the accessibility evaluation for the publication as a whole (there was a bug before whereby some of the evaluation report was retained, despite the failure of some chapters to be completely evaluated).
