### ISSUE TITLE
 Ace-GUI with WWNorton title did not export the data folder

### ISSUE THREAD

**Issue by GeorgeKerscher** [daisy/ace-gui#101]
I am testing titles for the CSUN Publisher's Faceoff. The WWnorton title runs in Ace-GUI at least three times faster than the command line. Once the ace-GUI finishes and I save the zip file, there is no data folder. The commandline does leave a folder.

This is the only title of the four so far that has had this problem. The title is in the secure Publisher EPUB folder of the DAISY Dropbox.

**Comment by danielweck** [comment]
I believe this is fixed in the latest version available in the release section of this GitHub project. The fix is to allow a maximum of 8 minutes of evaluation for each HTML document in the publication, beyond which point a timeout is triggered that fails the accessibility evaluation for the publication as a whole (there was a bug before whereby some of the evaluation report was retained, despite the failure of some chapters to be completely evaluated).
