### ISSUE TITLE
Ace-GUI crashing on Macmillan large book

### ISSUE THREAD

**Issue by GeorgeKerscher** [daisy/ace-gui#102]
The Macmillan title Modeling with Regression is in the Publisher's Face off Dropbox folder. I have used the Commandline to get a report, but another. I have rebooted my system several times.  every time I run the Ace-GUI it crashes for one reason or another. It is always an internal error.

**Comment by danielweck** [comment]
I believe this is fixed in the latest version available in the release section of this GitHub project. The fix is to allow a maximum of 8 minutes of evaluation for each HTML document in the publication, beyond which point a timeout is triggered that fails the accessibility evaluation for the publication as a whole (there was a bug before whereby some of the evaluation report was retained, despite the failure of some chapters to be completely evaluated).
