### ISSUE TITLE
Images not displaying

### ISSUE THREAD

**Issue by mattgarrish** [daisy/ace-gui#119]
Tried several books from the IDPF samples, both packaged and unpackaged, but all I get in the images tab are broken file icons.

<img width="254" alt="broken_file" src="https://user-images.githubusercontent.com/1565164/81932094-93da3780-95c1-11ea-945d-e5db1c111d32.PNG">

**Comment by clapierre** [comment]
We are getting the same behavior
Where we are getting no images is on a PC
Windows 10, with Ace GUI App 1.1.2
Exporting the Report does include the data directory with the images so that report.html does work showing the images, just not within the app itself.

On my Mac OS 14.0.3 with Ace 1.1.2 it works fine and images are displayed within the app and are exported correctly.

We are doing a training in Canada and this is making it difficult.
Thanks

**Comment by danielweck** [comment]
Fixed via a custom protocol handler (`file://` was blocked due to security restrictions in Electron):
https://github.com/daisy/ace-gui/blob/f16acdaebec27aefba61db8f2e2a44feda1911d7/src/main/main.js#L313-L319
