### ISSUE TITLE
Make info on GUI and CLI version more transparent

### ISSUE THREAD

**Issue by typopaul** [daisy/ace-gui#150]
Maybe I missed this info somehow on the download page of the Ace app or the github release page, but still I would like to point out:

It's not an issue per se, but since there are differences in the GUI version (currently v1.1.3) and the CLI (currently v1.2.5) some users get confused, which Ace version is practically running in the GUI app.

After a test run it is shown, that currently Ace v1.2.1  is build in the GUI v1.1.3.
Can this information made more visible in the release notes, the download website to the Ace GUI app and/or the Ace GUI app itself?

This would help a lot to prevent misunderstandings while implementing it into validation systems or speaking with other users (or trade customers, which likely have less intention on dealing with this topic and are happy about every little help).   

Thanks & best regards
Paul

**Comment by danielweck** [comment]
Same issue: https://github.com/daisy/ace/issues/362

Fixed via https://github.com/daisy/ace/commit/a585612fdb6622383ff0926bf4b9b6a680a2aeec and https://github.com/daisy/ace-gui/commit/b4211ea002c6cb41ed319148cedd13d001a9680f

Example in English:
* Ace command line tool: `Generated by DAISY Ace (1.2.6-alpha.4) on 03/02/2022, 00:17:43`
* Ace App (GUI): `Generated by DAISY Ace (1.2.6-alpha.4) on 03/02/2022, 00:17:43 [Ace App v1.1.4-alpha.1]`

As you can see, the main information remains Ace "core" (CLI = command line interface) which actually drives the accessibility evaluation and the production of the JSON+HTML reports, but we append Ace App (GUI) information in order to disambiguate version numbers.
