### ISSUE TITLE
Increase the default number of metadata entries to start at 25 or 50

### ISSUE THREAD

**Issue by clapierre** [daisy/ace-gui#154]
Its really annoying to always have to increase from 10 to 50 so I see all the metadata every time I look at these reports.

Please increase this :)
I thought I added this issue a year ago, but maybe only mentioned it in an email.
Thanks.

**Comment by danielweck** [comment]
Hello Charles, would you mind sharing an EPUB to reproduce this? Otherwise I will put together a sample by copy-pasting metadata items, but I always prefer to test with real-world examples.
In the meantime, I have pushed an update that increases the default number of rows to 50. The automated build should be ready within minutes: https://github.com/daisy/ace-gui/releases

**Comment by clapierre** [comment]
Sorry Daniel, I assume you figured it out since you closed it.
