### ISSUE TITLE
Run a file by dropping it on the application icon

### ISSUE THREAD

**Issue by rdeltour** [daisy/ace-gui#29]
from @ways2read:

> It would be great if I could drag the epub title onto the desktop icon, or use right click and choose Ace from there. 
> on Windows, I think you just need to be able to accept the EPUB filename as the first command line parameter, then dragging the file onto the icon should just work.

**Comment by danielweck** [comment]
This is already implemented.

**Comment by danielweck** [comment]
Currently implemented in master branch, not yet available in official release.

**Comment by ways2read** [comment]
Confirming this is working for me in 1.0.0-rc-2.26
So I can drag an EPUB onto the icon in the Windows desktop, I can configure my shell menu so that I can right click on an EPUB in File Explorer and have the option to "Check EPUB in Ace", and I can launch programatically from another app/batch file.

The confirmation message may be unnecessary, but I can live with that.

**Comment by danielweck** [comment]
Note that there is no "job queue" feature in the present application design. With the current implementation, any attempt to start an evaluation during an existing job results in a information message (modal popup dialog box) inviting the user to try again.
